### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by moebiuseye** [processone/oneteam#1]
Hi. I was wondering where I could find installation instructions for this, especially for instructions for the linux tar.bz that's available on the oneteam.im website.

**Comment by moebiuseye** [comment]
Also, it seams that the xpi for firefox isn't compatible with firefox 44.0 With wich version is it compatible?

**Comment by rolandixor** [comment]
This project is clearly abandonware. You're probably not going to get a meaningful reply.
